[protection]
psw_gateway = "false"

[cookie]
cookie_name   = "SunlightCalendar"
cookie_hash_psw   = "Az3rTy-1465"
cookie_expiry_duration = 30

[page]
page_title      = "Daylight Calendar Generator"
page_icon       = "☀️" # Sun emoji for favicon
layout          = "centered"
footer          = """<style> a:link , a:visited{ color: blue; background-color: transparent; text-decoration: underline; } a:hover, a:active { color: red; background-color: transparent; text-decoration: underline; } .footer { position: fixed; left: 0; bottom: 0; width: 100%; background-color: #f0f2f6; color: #666; text-align: center; padding: 15px 0; border-top: 1px solid #e0e0e0; } </style> <div class="footer"> <p style="margin: 0;">☀️ Made with love by <a href="https://chloelavrat.com" target="_blank"><bold>Chloé Lavrat</bold></a> ❤️</p> </div>"""
hide_menu_style = "<style>#MainMenu {visibility: hidden;}</style>"

[data]
database_path = "./database"

